"""Type stubs for pyodide.ffi (Pyodide foreign-function interface)."""

from collections.abc import Callable, Generator, Iterator
from typing import override

class JsProxy:
    """Opaque type representing a JavaScript value proxied into Python."""

    # Dynamic attribute access — JS properties are resolved at runtime.
    def __getattr__(self, name: str) -> "JsProxy": ...
    def __getitem__(self, key: int | str) -> "JsProxy": ...
    def __setitem__(self, key: int | str, value: object) -> None: ...

    # Calling — JS functions proxied into Python are callable.
    def __call__(self, *args: object, **kwargs: object) -> "JsProxy": ...

    # Awaiting — JS Promises are awaitable in Pyodide.
    def __await__(self) -> Generator[object, None, "JsProxy"]: ...

    # Iteration — JS iterables / arrays.
    def __iter__(self) -> Iterator["JsProxy"]: ...
    def __len__(self) -> int: ...

    # Truthiness & identity
    def __bool__(self) -> bool: ...

    # Comparison — Pyodide delegates to JS comparison semantics.
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...

    # Conversions
    @override
    def __str__(self) -> str: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...

def create_proxy(obj: Callable[..., object]) -> JsProxy:
    """Wrap a Python callable so it can be used as a JS callback."""
    ...

def to_js(
    obj: object,
    *,
    dict_converter: Callable[..., object] | None = ...,
    default_converter: Callable[..., object] | None = ...,
    depth: int = ...,
) -> JsProxy:
    """Convert a Python object to a JavaScript proxy."""
    ...
